Mysite/Mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^mysites/login$', 'my_profile.views.login',name="login"),
    url(r'^mysites/registration$', 'my_profile.views.register_user',name="register"),
    url(r'^mysites/registeration_successful$', 'my_profile.views.register_success',name='success'),
    url(r'^mysites/auth$', 'my_profile.views.auth_view',name='index'),
    url(r'^mysites/invalid_page$', 'my_profile.views.invalid_login'),
    url(r'^mysites/my_home$', 'my_profile.views.loggedin', name="home"),
    url(r'^mysites/$', 'my_profile.views.login',name="logout"),
    url(r'^mysites/view_posts$', 'my_profile.views.eventlist',name="comments"),
    url(r'^(?P<p_id>[0-9]+)', 'my_profile.views.add_comments',name='logg'),
    url(r'^mysites/change_profile$', 'my_profile.views.change_profile',name='change'),
    url(r'^mysites/update_successful$', 'my_profile.views.update_success',name='update'),
]
 #url(r'^mysites/edit_profile/(<p_id>[0-9]+)$', 'my_profile.views.change_profile',name='change'),

Mysite/my_profile/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User 

class User_Profile(models.Model):

    user = models.OneToOneField(User)
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=30)
    age = models.CharField(max_length=5)
    def __str__(self):
        return "%s,%s,%s,%s" % (self.name,self.address,self.phone,self.age)

class Posts(models.Model):		
    title = models.CharField(max_length=50)
    text = models.TextField()
    def __str__(self):
    	return self.title
		
class Comments(models.Model):
	name = models.CharField(max_length=50,null=True)
	text = models.TextField()
	post = models.ForeignKey(Posts)
	def __str__(self):
		return self.text
		
		

Mysite/my_profile/forms.py
from django import forms
from django.contrib.auth.models import User
from my_profile.models import User_Profile
from my_profile.models import Posts
from my_profile.models import Comments


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:

        model = User
        fields = ('username', 'password')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = User_Profile
        fields = ('name', 'address', 'phone', 'age')

class CommentsForm(forms.ModelForm):
	
	class Meta:
		model = Comments
		fields = ('text',)

class PostsForm(forms.ModelForm):
    class Meta:
    	model=Posts
    	fields =('title','text')
						

Mysite/my_profile/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib import auth
from my_profile.forms import UserForm, UserProfileForm,CommentsForm,PostsForm
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from my_profile.models import User_Profile,Posts,Comments
from django.core.mail import send_mail
from django.http import Http404

# Create your views here.

def login(request):
    return render_to_response('index1.html')

def register_user(request):
    context = RequestContext(request)
    registered = False
    user_form = UserForm()
    profile_form = UserProfileForm()
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
        if registered:
            return HttpResponseRedirect('/mysites/registeration_successful')
        
    return render_to_response('new_registration.html',
        {'user_form': user_form, 'profile_form': profile_form,
        'registered': registered},
              context)

def register_success(request):
    return render_to_response("successful_registration.html")

@csrf_exempt
def update_success(request):
    return render_to_response("update.html")

@csrf_exempt
def auth_view(request):
    username = request.POST.get("username")
    password = request.POST.get("password")
    user = auth.authenticate(username=username, password=password)
    if user is not None:
        auth.login(request, user)
        email_subject = 'Account confirmation'
        email_body = "Hey %s, thanks for Login."%(username)
        send_mail(email_subject, email_body, 'safeer.sayone@gmail.com',['safeersayed1990@gmail.com'], fail_silently=False)
        return HttpResponseRedirect('/mysites/my_home')
    else:
        return HttpResponseRedirect('/mysites/invalid_page')

@csrf_exempt
def invalid_login(request):
    return render_to_response("invalid_page.html")

@csrf_exempt
def loggedin(request):
    details = User_Profile.objects.get(user=request.user)
    return render_to_response("my_home.html",
        {"full_name": details.name, 'address': details.address,
        'phone': details.phone, 'age': details.age})

def eventlist(request):
    posts=Posts.objects.all()
    context=RequestContext(request)
    return render_to_response('posts.html',{'post':posts},context)

@csrf_exempt
def change_profile(request):
    context=RequestContext(request)
    user = request.user
    p = User_Profile.objects.get(user=user)
    print "lkblkjbhlkjhblkbhj"
    if request.method == "POST":
      p.name = request.POST['name']
      print request.POST['name'], "======"
      p.address = request.POST['address']
      p.phone = request.POST['phone']
      p.age = request.POST['age']
      p.save()
    return render_to_response('change_profile.html',{'profile':p,"user": user},context)
        

@csrf_exempt
def add_comments(request,p_id):
    post = Posts.objects.get(pk=p_id)
    if request.method == 'POST':
      form = CommentsForm(request.POST)
      if form.is_valid():
        p = form.save(commit=False)
        p.name = request.user
        p.post =  post
        p.save()
    context = RequestContext(request)
    c = CommentsForm()
    return render_to_response('add_comments.html',
              {'post': post, 'textform': c
                 },context
               )

Mysite/my_profile/templates/add_comments.html
<html>
<head>

</head>
<body>
<p align="right"><a href="{% url 'comments' %}">Back</a> | <a href="{% url 'logout'%}">Logout</a></p>
<h2>{{ post.title }}</h2>

<div class="content">
    <p>
        {{ post.text }}
   
</div>

{% if post.comments_set.all %}
<h2>Comments</h2>
<div class="comments">
    {% for comment in post.comments_set.all %}
        <span>
           <h3># {{ comment.name }} : </h3>
        </span>
         <span>
         <p>
           
{{ comment.text }}
            
         </p>
         </span>
    {% endfor %}
</div>
{% endif %}

<br />

<h2>Add Comment</h2>

<form action="{% url 'logg' post.id %}" method="post">
    
   
        {{ textform.text }}<br/>
    <input type="submit" value="Submit" />
</form>
</body>
</html>

Mysite/my_profile/templates/change_profile.html
<p align="right"><a href="{% url 'home' %}">Back</a> | <a href="{% url 'logout'%}">Logout</a></p>
<h2><p align="center">Update Profile</p></h2>
<form action="{% url 'change'%}" method="POST">
<br/>
<br/>
<br/>
<p align="center">
<table>
<tr>
<td>Name:</td>
<td><input type="text" value="{{profile.name}}" name="name"></td>
</tr>
<tr>
<td>Address:</td>
<td><input type="text" value="{{profile.address}}" name="address"></td>
</tr>
<tr>
<td>Phone:</td>
<td><input type="text" value="{{profile.phone}}" name="phone"></td>
</tr>
<tr>
<td>Age:</td>
<td><input type="text" value="{{profile.age}}" name="age"></td>
</tr>
<tr>
</table></p>
<p align="center"><input type="submit" value="Update"></p>
</form>

Mysite/my_profile/templates/dd/index.html
<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
    <title>My Persionals</title>
    
    
    <link rel="stylesheet" href="{{STATIC_URL}}'css/reset.css'">

    <link rel='stylesheet prefetch' href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900|RobotoDraft:400,100,300,500,700,900'>
<link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>

        <link rel="stylesheet" href="{{STATIC_URL}}'css/style.css'">

    
    
    
  </head>

  <body>

    
<!-- Form Mixin-->
<!-- Pen Title-->
<div class="pen-title">
  <h1>My Personal Login Form</h1><span>Pen <i class='fa fa-paint-brush'></i> + <i class='fa fa-code'></i> by <a href='http://google.co.in'>Google</a></span>
</div>
<!-- Form Module-->
<div class="module form-module">
  <div class="toggle"><i class="fa fa-times fa-pencil"></i>
    <div class="tooltip">Click Me</div>
  </div>
  <div class="form">
    <h2>Login to your account</h2>
    <form>
      <input type="text" placeholder="Username"/>
      <input type="password" placeholder="Password"/>
      <button>Login</button>
    </form>
  </div>
  <div class="form">
    <h2>Create an account</h2>
    <form>
      <input type="text" placeholder="Username"/>
      <input type="password" placeholder="Password"/>
      <input type="email" placeholder="Email Address"/>
      <input type="tel" placeholder="Phone Number"/>
      <button>Register</button>
    </form>
  </div>
  <div class="cta"><a href="http://andytran.me">Forgot your password?</a></div>
</div>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='js/da0415260bc83974687e3f9ae.js'></script>

        <script src="js/index.js"></script>

    
    
    
  </body>
</html>

Mysite/my_profile/templates/index1.html
<!DOCTYPE html>
<html>
<head>
</head>
<body>


{% block content %}

 {% if form.errors %}
   <p class="error">Sorry, this is not a valid username or password</p>
 {% endif %}
 <title>My Profile</title>
 <div style="margin-left:0px;margin-top:250px;">
 <form action="{% url 'index' %}" method="post">{% csrf_token %}
 <h2><p align="center">Login</p></h2>
 <p align="center">
 <label for="username">User Name</label>
 <input type="text" name="username" value="" id="username"><br/><br/>
 <label for="password">Password</label>&nbsp&nbsp&nbsp
 <input type="password" name="password" value="" id=password><br/><br/>
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 <a href="/mysites/registration">New User ?</a>
 <input type="submit" value="Login"/></p>
 </form></div>


 {% endblock %}
 </body>
</html>

Mysite/my_profile/templates/index2.html
{% block content %}

 <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
 <div style="margin-left:0px;margin-top:250px;">
 {% if form.errors %}
   <p class="error">Sorry, this is not a valid username or password</p>
 {% endif %}
 <title>My Profile</title>

 <form action="/mysites/auth" method="post">{% csrf_token %}
 <p align="center">
 <label for="username">User Name</label>
 <input type="text" name="username" value="" id="username"><br/><br/>
 <label for="password">Password</label>&nbsp&nbsp&nbsp
 <input type="password" name="password" value="" id=password><br/><br/>
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 <a href="/mysites/registration">New User ?</a>
 <input type="submit" value="Login"/></p>
 </form></div>


 {% endblock %}

Mysite/my_profile/templates/invalid_page.html
{%block content%}

<h2><p align="center">Invalid User Access</p></h2>
<p align="center"><a href="/mysites/login">Try again</a></p>

{%endblock%}

Mysite/my_profile/templates/my_home.html
{% block content%}
<title>My Home</title>
<h3><p align="right">Hi {{full_name.capitalize}}</p></h3>
<p align="right"><font color="Green"><blink>Online</blink></font><br/>
<a href="{% url 'change' %}">Edit Profile</a>| 
<a href="/mysites/">LogOut</a></p>
<br/>
<br/>
<br/>
<p align="center">
<table>
<tr>
<td>Name:</td>
<td>{{full_name.capitalize}}</td>
</tr>
<tr>
<td>Address:</td>
<td>{{address}}</td>
</tr>
<tr>
<td>Phone:</td>
<td>{{phone}}</td>
</tr>
<tr>
<td>Age:</td>
<td>{{age}}</td>
</tr>
</table></p>
<p align="center"><a href="/mysites/view_posts">View Posts</a></p>
{%endblock%}

Mysite/my_profile/templates/new_registration.html
{% block content %}
<title>New Account</title>
<h2><p align="center">New User</p></h2>
<form action="/mysites/registration" method="post">
{% csrf_token %}
{% if registered %}
<h3>Thank you for registering</h3>
{% else %}
<p align="center">
<table>
 <tr>
  <td>Name</td>
 </tr>
 <tr>
  <td>{{profile_form.name}}</td>
 </tr>
 <tr>
  <td>Address</td>
 </tr>
 <tr>
  <td>{{profile_form.address}}</td>
 </tr>
 <tr>
  <td>Phone</td>
 </tr>
 <tr>
  <td>{{profile_form.phone}}</td>
 </tr>
 <tr>
  <td>Age</td>
 </tr>
 <tr>
  <td>{{profile_form.age}}</td>
 </tr>
 <tr>
  <td>User Name</td>
 </tr>
 <tr>
  <td>{{user_form.username}}{{user_form.username.errors}}</td>
 </tr>
 <tr>
  <td>Password</td>
 </tr>
 <tr>
  <td>{{user_form.password}}{{user_form.username.errors}}</td>
 </tr>
 <tr><td></td></tr>
 <tr>
  <td>
  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
  <a href="{% url 'login' %}">SignUp</a>&nbsp<input type="submit" value="Confirm"/></td>
 </tr>
</table></p>
</form>
{%endif%}
{%endblock%}

Mysite/my_profile/templates/posts.html
<p align="right"><a href="{% url 'home' %}">Back</a> | <a href="{% url 'logout'%}">Logout</a></p>
<ul>
	{% for p in post %}
         <li><a href="{% url 'logg' p.id %}">{{ p.title}}</a></li>
    {% endfor %} 
</ul>

Mysite/my_profile/templates/safeer.html
<!DOCTYPE html>
<html>
<head>
</head>
<body>


{% block content %}

 {% if form.errors %}
   <p class="error">Sorry, this is not a valid username or password</p>
 {% endif %}
 <title>My Profile</title>
 <div style="margin-left:0px;margin-top:250px;">
 <form action="{% url 'index' %}" method="post">{% csrf_token %}
 <h2><p align="center">Login</p></h2>
 <p align="center">
 <label for="username">User Name</label>
 <input type="text" name="username" value="" id="username"><br/><br/>
 <label for="password">password</label>&nbsp&nbsp&nbsp
 <input type="password" name="password" value="" id=password><br/><br/>
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 &nbsp&nbsp&nbsp&nbsp
 <a href="/mysites/registration">New User ?</a>
 <input type="submit" value="Login"/></p>
 </form></div>


 {% endblock %}
 </body>
</html>

Mysite/my_profile/templates/successful_registration.html
{%block content%}
<title>Registration Successful</title>

<h2><p align="center">You have successfully registered</p></h2>
<p align="center">Click <a href="/mysites/login">here </a>to login again</p>
{%endblock%}

Mysite/my_profile/templates/update.html
{%block content%}
<title>Updation Successful</title>

<h2><p align="center">You have successfully update details !!!</p></h2>
<p align="center"><a href="{% url 'home' %}">Home</a></p>
{%endblock%}